### ISSUE TITLE
netdata homepage widget gives "NaN undefined" for Disk Space Used and Disk Space Avaiable

### ISSUE THREAD

**Issue by ghost** [Organizr/docker-base#12]
![image](https://github.com/user-attachments/assets/86665915-a735-4598-938e-b60c0e5fba3f)
![image](https://github.com/user-attachments/assets/ff49cca0-3c25-4d34-8281-887c186368f3)
Right now adding the netdata widget does not show free space and used space, giving a NaN undefined error

```
  organizr:
    container_name: organizr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=America/Edmonton
    ports:
      - 82:80
    volumes:
      - /mnt/docker/organizr:/config
    networks:
      - dockerbridge
    image: ghcr.io/organizr/organizr
```

Setup:
512GB at root, plus 1tb as a download drive
four 14tb drives added to a mergerfs pool
